--1.  What is the total number of rows in all 3 tables in the database?
SELECT *
FROM Customer
FULL OUTER JOIN Transactions ON Customer.customer_id = Transactions .cust_id
FULL OUTER  JOIN prod_cat_info ON Transactions.prod_cat_cdoe = prod_cat_info.prod_cat_code"
==================================================================================================
--2 What is the total number of transactions that have a return?
SELECT COUNT(transaction_id)
FROM Transactions"
===================================================================================================
--3 As you would have noticed, the dates provided across the datasets are not in a correct format. As first steps,
--pls convert the date variables into valid date formats before proceeding ahead.
SELECT TRANSACTION_ID, TO_CHAR(TRAN_DATE, 'DD/MM/YY')
FROM TRANSACTIONS
====================================================================================================
--5 Which product category does the sub-category "DIY" belong to?
Select prod_cat, prod_subcat
FROM PROD_CAT_INFO
Where prod_subcat = DIY"
========================================================================================================
DATA ANALYSIS
--1. Which channel is most frequently used for transactions?
SELECT STORE_TYPE, COUNT(STORE_TYPE)
FROM TRANSACTIONS
GROUP BY STORE_TYPE
==========================================================================================================
--2. What is the count of Male and Female customers in the database?
SELECT  GENDER, COUNT(1)"
FROM Customer
With (NOLOCK)
GROUP BY GENDER
=========================================================================================================
--3. From which city do we have the maximum number of customers and how many?
SELECT  Customer.city_code, Count(transactions.cust_id)(1)
FROM Customer
INNER JOIN Transactions on Customer.Customer_ID = Transactions.cust_id
With (NOLOCK)
GROUP BY Customer.city_code
==========================================================================================================
--4. How many sub-categories are there under the Books category?
SELECT prod_cat, COUNT(prod_subcat)
FROM PROD_CAT_INFO
Where prod_cat = Books
GROUP BY prod_cat
===========================================================================================================
--5. What is the maximum quantity of products ever ordered?
SELECT MAX(QTY)
FROM Transactions
============================================================================================================
--6. What is the net total revenue generated in categories Electronics and Books?
SELECT PROD_CAT_INFO.PROD_CAT,  SUM(TOTAL_AMT) AS TOTAL_REVENUE"
FROM TRANSACTIONS
INNER JOIN PROD_CAT_INFO ON TRANSACTIONS .PROD_CAT_CDOE = PROD_CAT_INFO .PROD_CAT_CODE
Group by PROD_CAT_INFO.PROD_CAT, TRANSACTIONS.STORE_TYPE
Having prod_cat = "Electronics" Or "Books""
============================================================================================================
--7. How many customers have >10 transactions with us, excluding returns?
SELECT TRANSACTION_ID, COUNT(CUST_ID)
FROM TRANSACTIONS
GROUP BY TRANSACTION_ID
============================================================================================================
--8. What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?
SELECT PROD_CAT_INFO.PROD_CAT, TRANSACTIONS.STORE_TYPE, SUM(TOTAL_AMT) AS TOTAL_REVENUE
FROM PROD_CAT_INFO
INNER JOIN TRANSACTIONS ON PROD_CAT_INFO.PROD_CAT_CODE = TRANSACTIONS.PROD_CAT_CDOE
Where STORE_TYPE = "Flagship stores"
Group by PROD_CAT_INFO.PROD_CAT, TRANSACTIONS.STORE_TYPE
Having prod_cat = "Electronics" Or "Clothing"
==================================================================================================================
--9.What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.
Select gender, prod_cat, SUM(TOTAL_AMT) AS "prod sub-cat"
FROM Customer
Inner join transactions on Customer .Customer_id = transactions .cust_id
Inner join prod_cat_info on transactions.prod_cat_cdoe  = prod_cat_info.prod_cat_code
Where gender = "M"
Group by gender, prod_cat
Having prod_cat = "Electronics"
=====================================================================================================================
--10. What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
SELECT top 5 * FROM TRANSACTIONS
ORDER BY prod_subcat
======================================================================================================================
--11. For all customers aged between 25 to 35 years 
--What is the net total revenue generated by these consumers in last 30 days of transactions?
SELECT SUM(TOTAL_AMT)
FROM TRANSACTIONS

--12.find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data?
SELECT * FROM CUSTOMERS
INNER JOIN TRANSACTIONS ON CUSTOMERS.CUSTOMER_ID = TRANSACTIONS.CUST_ID
